export const universities = {
  zh: {
    eu: [
      '伦敦大学学院',
      '格拉斯哥大学',
      '曼彻斯特大学',
      '伯尔尼大学',
      '瓦格宁根大学',
      '特温特大学',
    ],
    na: [
      '宾夕法尼亚州立大学',
      '加州大学圣巴巴拉分校',
      '威斯康辛大学麦迪逊分校',
      '亚利桑那州立大学',
      '麦吉尔大学',
      '麦克马斯特大学',
    ],
    asia: [
      '香港大学',
      '香港中文大学',
      '香港科技大学',
      '香港理工大学',
      '新加坡国立大学',
      '东京大学',
    ],
    oceania: [
      '墨尔本大学',
      '悉尼大学',
      '昆士兰大学',
      '新南威尔士大学',
      '奥克兰大学',
      '坎特伯雷大学',
    ],
    africaAndLA: [
      '南非金山大学',
      '洛斯安第斯大学',
      '开普敦大学',
      '智利天主教大学',
      '智利大学',
      '布宜诺斯艾利斯大学',
    ],
  },
  en: {
    eu: [
      'University College London',
      'University of Glasgow',
      'University of Manchester',
      'University of Bern',
      'Wageningen University & Research',
      'University of Twente',
    ],
    na: [
      'Pennsylvania State University',
      'University of California, Santa Barbara',
      'University of Wisconsin-Madison',
      'Arizona State University',
      'McGill University',
      'McMaster University',
    ],
    asia: [
      'The University of Hong Kong',
      'The Chinese University of Hong Kong',
      'The Hong Kong University of Science and Technology',
      'The Hong Kong Polytechnic University',
      'National University of Singapore',
      'The University of Tokyo',
    ],
    oceania: [
      'The University of Melbourne',
      'The University of Sydney',
      'The University of Queensland',
      'The University of New South Wales',
      'The University of Auckland',
      'The University of Canterbury',
    ],
    africaAndLA: [
      'University of Johannesburg',
      'University of Los Andes',
      'University of Cape Town',
      'Catholic University of Chile',
      'University of Chile',
      'University of Buenos Aires',
    ],
  },
}
